### ISSUE TITLE
'webpack/lib/RequestShortener'和'webpack/lib/ModuleFilenameHelpers'

### ISSUE THREAD

**Issue by strongcode9527** [wuomzfx/webpack-babel-plugin#1]
相学长您好，在网上看了您的tree-shaking文章，学到了很多知识，而且自己也成功实现了关于class进行tree-shaking。但是我在研究您的插件的时候，有两个webpack的内部插件不知道是什么意思。您能给我个相关文档吗？我在webpack官网和google上面找了半天，也没有找到。。。

```

// 第二个我可以猜到是进行文件过滤使用。但第一个真的不知道是干什么用的。。
const RequestShortener = require('webpack/lib/RequestShortener') 


const ModuleFilenameHelpers = require('webpack/lib/ModuleFilenameHelpers')

```

**Comment by wuomzfx** [comment]
buildError 那段代码，我也是直接从uglifyjs那边copy过来的，RequestShortener这种内部工具方法，估计就是没有什么文档的。RequestShortener可能是抛错时，将出错时的代码资源精简显示。我觉得这些不是关键部分大致看下就好了。真的想研究下的话，可以去跑跑代码看它真的干了什么。

**Comment by strongcode9527** [comment]
@wuomzfx 好的。不过您的源码，基本看懂了，也跑了一遍。倒是没什么问题。不过webpack的文档真是扯，自定义webpack插件，这些常用的内部函数，竟然连提都不提，怪不得webpack官方文档一直挨骂。
